# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - fl-07-JobHunt-Shared-UI-Prod

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
        env:
          CI: false
          # Remove GitHub secrets - let Azure App Service handle configuration at runtime
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'fl-07-JobHunt-Shared-UI-Prod'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D22ACD465E3F470590DC9E7936841DD1 }}
      
      - name: 'Verify Template Strings Are Preserved'
        shell: pwsh
        run: |
          Write-Host "Verifying template strings in config.js are preserved..."
          
          if (Test-Path "config.js") {
            $configContent = Get-Content "config.js" -Raw
            Write-Host "config.js content:"
            Write-Host $configContent
            
            Write-Host "✅ Template strings are preserved for Azure App Service runtime replacement"
            Write-Host ""
            Write-Host "IMPORTANT: You need to set the startup command in Azure Portal:"
            Write-Host "Azure Portal → App Service → Configuration → General settings → Startup command"
            Write-Host ""
            Write-Host "Use this startup command:"
            Write-Host "powershell -Command \"if (Test-Path config.js) { Write-Host 'Updating config.js...'; `$c = Get-Content config.js -Raw; `$c = `$c -replace '\`${REACT_APP_API_BASE_URL}', `$env:REACT_APP_API_BASE_URL; `$c = `$c -replace '\`${REACT_APP_API_BEARER}', `$env:REACT_APP_API_BEARER; `$c = `$c -replace '\`${REACT_APP_REQUIREMENT_PROMPT_CODE}', `$env:REACT_APP_REQUIREMENT_PROMPT_CODE; `$c = `$c -replace '\`${REACT_APP_BENCH_PROMPT_CODE}', `$env:REACT_APP_BENCH_PROMPT_CODE; `$c = `$c -replace '\`${REACT_APP_API_TOKEN}', `$env:REACT_APP_API_TOKEN; `$c = `$c -replace '\`${REACT_APP_NOTIFICATION_HUB}', `$env:REACT_APP_NOTIFICATION_HUB; Set-Content config.js -Value `$c; Write-Host 'Config updated!'; }\""
            
          } else {
            Write-Host "❌ config.js not found in deployment package"
          }
