# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - fl-07-JobHunt-Shared-UI-Prod

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
        env:
          CI: false
          # Remove GitHub secrets - let Azure App Service handle configuration at runtime
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'fl-07-JobHunt-Shared-UI-Prod'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D22ACD465E3F470590DC9E7936841DD1 }}
      
      - name: 'Replace Template Strings with Azure App Service Configuration'
        shell: pwsh
        run: |
          Write-Host "Replacing template strings in config.js..."
          
          if (Test-Path "config.js") {
            # Read the config.js file
            $configContent = Get-Content "config.js" -Raw
            
            Write-Host "Original config.js content:"
            Write-Host $configContent
            
            # Replace template strings with placeholder values that will be replaced at runtime
            # We'll use a different approach - set these as app settings and let the app read them
            
            # For now, let's just ensure the template strings are preserved
            Write-Host "Template strings preserved for Azure App Service runtime replacement"
            Write-Host "Azure App Service will replace these values using application settings"
            
            # Show what the final config should look like
            Write-Host "Expected replacement values from Azure App Service:"
            Write-Host "REACT_APP_API_BASE_URL should be replaced with: https://fl-07-jobhunt-shared-api-prod.azurewebsites.net/api12/"
            Write-Host "REACT_APP_API_BEARER should be replaced with: [Your Bearer Token]"
            Write-Host "REACT_APP_REQUIREMENT_PROMPT_CODE should be replaced with: REQRMNT"
            Write-Host "REACT_APP_BENCH_PROMPT_CODE should be replaced with: RESUME"
            Write-Host "REACT_APP_API_TOKEN should be replaced with: [Your API Token]"
            Write-Host "REACT_APP_NOTIFICATION_HUB should be replaced with: https://fl-07-jobhunt-shared-api-test.azurewebsites.net/notificationHub"
            
          } else {
            Write-Host "config.js not found in deployment package"
          }
